# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

movingRMS <- function(input_data, intwind) {
    .Call('_EMGhelpeR_movingRMS', PACKAGE = 'EMGhelpeR', input_data, intwind)
}

